### ISSUE TITLE
Fail to write Gemfile.lock

### ISSUE THREAD

**Issue by ocefpaf** [David-Byrne/jekyll-diff-action#2]
I'm getting a

    There was an error while trying to write to
    `/github/workspace/Gemfile.lock`.

when trying to use this action. Seems to be related to https://github.community/t5/GitHub-Actions/GitHub-Docker-container-action-cannot-write-to-github-workspace/td-p/32017

Not sure how to fix that. I guess we would need to adjust the Dockerfile?

**Comment by David-Byrne** [comment]
Ah, more permission issues... In the case of [your repo](https://github.com/oceanhackweek/oceanhackweek.github.io), this is occurring because there's no `Gemfile.lock` and I'd guess Jekyll tries to create one by default. If you commit your `Gemfile.lock` file, then the action won' have to create it and the build should pass.

I'll also try come up with a more general purpose solution to stop these sort of problems occurring.

**Comment by ocefpaf** [comment]
Thanks! I'll commit the file for now.
